DROP TABLE IF EXISTS TRANSFERS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	UID VARCHAR PRIMARY KEY,
	EMAIL VARCHAR NOT NULL UNIQUE,
	SALDO INT CHECK(SALDO >= 0) DEFAULT 0,
	FECHA DATE DEFAULT CURRENT_DATE
);

CREATE TABLE TRANSFER (
	ID SERIAL PRIMARY KEY,
	ORIGEN VARCHAR,
	FOREIGN KEY(ORIGEN) REFERENCES USERS(UID),
	DESTINO VARCHAR,
	FOREIGN KEY(DESTINO) REFERENCES USERS(UID),
	VALOR INT CHECK(VALOR > 0)
);